# Generated by Django 4.1.3 on 2022-11-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=60)),
                ("client_company", models.CharField(max_length=60)),
                ("client_phone", models.IntegerField()),
                ("client_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.IntegerField()),
                ("project_title", models.CharField(max_length=60)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("DD", "Development Department"),
                            ("MD", "Managers Department"),
                            ("APPD", "Application Department"),
                            ("ACCD", "Accounts Department"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "project_priority",
                    models.CharField(
                        choices=[
                            ("DD", "Development Department"),
                            ("MD", "Managers Department"),
                            ("APPD", "Application Department"),
                            ("ACCD", "Accounts Department"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("work_status", models.CharField(max_length=10)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.client"
                    ),
                ),
            ],
        ),
    ]
